name: Elyra Tests (1.x)
on:
  push:
    branches:
    - master
  pull_request:
    branches: '*'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version: [ '3.6', '3.7', '3.8' ]
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
        architecture: 'x64'
    - name: Set up Node
      uses: actions/setup-node@v1
      with:
         node-version: '12.13'
    - name: Display dependency info
      run: |
        python --version
        node --version
        npm --version
        pip --version
    - name: Create npm configuration for authentication
      run: |
        echo "@elyra-ai:registry=https://npm.pkg.github.com/" >> ~/.npmrc
        echo "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_PERSONAL_TOKEN }}" >> ~/.npmrc
        echo "always-auth=true" >> ~/.npmrc
        echo "scripts-prepend-node-path=true" >> ~/.npmrc
        echo "prefix=~/.npm-global" >> ~/.npmrc
        mkdir -p ~/.npm-global
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip wheel flake8 notebook jupyterlab
    - name: Install NPM dependencies
      run: |
        sudo apt install yarn
        npm install -g lerna@3.19.0
        npm install -g rimraf@3.0.0
        npm install -g typescript@3.7.3
        npm install -g yarn@1.21.0
    - name: Build
      run: |
        export PATH=~/.npm-global/bin:$PATH
        make install
    - name: Test with pytest
      run: |
        pip install pytest pytest-console-scripts
        pytest
    - name: Collect logs
      if: failure()
      run: cat /tmp/jupyterlab-debug-*.log
